owner: la-test
repo: sbx-upptime

sites:
  - name: Least Authority
    url: https://www.leastauthority.com/
  - name: Private Storage
    url: https://private.storage/
  - name: Winden
    url: https://winden.app/
  - name: HRO Cloud
    url: https://thissitedoesnotexist.koj.co

status-website:
  baseUrl: /sbx-upptime
  logoUrl: https://raw.githubusercontent.com/la-test/sbx-upptime/main/assets/upptime-icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This site monitor public resources of LA
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
