owner: la-test
repo: sbx-upptime

sites:
  - name: Least Authority - website
    url: https://www.leastauthority.com/
  - name: Private Storage - website
    url: https://private.storage/
  - name: Winden - website
    url: https://winden.app/
  - name: Magic Wormhole - mailbox
    url: https://mailbox.mw.leastauthority.com/
    icon: https://leastauthority.com/wp-content/uploads/2020/07/wormhole2-e1596622143647.png
  - name: Magic Wormhole - relay
    url: https://relay.mw.leastauthority.com/
    icon: https://leastauthority.com/wp-content/uploads/2020/07/wormhole2-e1596622143647.png
  - name: HRO Cloud - storage001
    check: "tcp-ping"
    url: storage001.deerfield.leastauthority.com
    port: 8898
    icon: https://leastauthority.com/wp-content/uploads/2021/05/TahoeLAFS.png
  - name: HRO Cloud - storage002
    check: "tcp-ping"
    url: storage002.deerfield.leastauthority.com
    port: 8898
    icon: https://leastauthority.com/wp-content/uploads/2021/05/TahoeLAFS.png
  - name: HRO Cloud - storage003
    check: "tcp-ping"
    url: storage003.deerfield.leastauthority.com
    port: 8898
    icon: https://leastauthority.com/wp-content/uploads/2021/05/TahoeLAFS.png

status-website:
  baseUrl: /sbx-upptime
  logoUrl: https://raw.githubusercontent.com/la-test/sbx-upptime/main/assets/upptime-icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This site monitor public resources of LA
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
